### ISSUE TITLE
Distance Search Not Working Properly

### ISSUE THREAD

**Issue by LittleGreenViper** [radius314/sandwich#18]
This concerns the "positive" values of geo_width, in the search URI.

Here's an example:

If we go to the GNYR server directly:

https://bmlt.newyorkna.org/main_server//client_interface/json/?switcher=GetSearchResults&lat_val=40.902778&long_val=-73.344167&geo_width=100

We get almost 1000 responses.

However, the same thing to the Sandwich server gives the same response as if it were -30 (Find around 30 meetings):

https://na-bmlt.org/_/sandwich//client_interface/json/?switcher=GetSearchResults&lat_val=40.902778&long_val=-73.344167&geo_width=100

These two URIs should return exactly the same values.

**Comment by LittleGreenViper** [comment]
Just to add some information, it appears to work correctly within a close range of the search center; maybe 25 miles. It is a problem over that.
For rural areas, we probably need to be able to go out 100 miles.
Don't forget that many nations prefer Km, so the geo_width_km field will be used then.

**Comment by radius314** [comment]
Discussed with @LittleGreenViper that we will search the largest current range (200 miles) and then aggregate and sort the result until we satisfy the geo_width / geo_width_km.

+ is number of miles
- is number of results

**Comment by radius314** [comment]
Upon further review this is unnecessary, we can just return that amount of returns and then apply the respective sort.

**Comment by radius314** [comment]
@LittleGreenViper this has been fixed and deployed to the worldwide sandwich server.  Please verify.

https://github.com/radius314/sandwich/commit/e2adfcbb7e95a48c8082f1b28097767b8c77ad45

**Comment by LittleGreenViper** [comment]
It seems to be working. I'll need to spend more time in fine-tuned testing, but this seems to match the GNYR server.
