### ISSUE TITLE
Format Responses Not Working Properly

### ISSUE THREAD

**Issue by LittleGreenViper** [radius314/sandwich#19]
This issue concerns matching format IDs between the ones returned during an initial ?switcher=GetFormats call (Returns all possible format codes), and the formats returned as part of a search query (Returns only the formats that are used within that search).

First, a working example. I will use the GNYR semantic interface.

If you call this URI, you will get all possible formats on the GNYR server:

https://bmlt.newyorkna.org/main_server/client_interface/json/?switcher=GetFormats

This is a search only:

https://bmlt.newyorkna.org/main_server/client_interface/json/?switcher=GetSearchResults&services=1001

Now, do a search, and set the "get_used_formats=1" flag:

https://bmlt.newyorkna.org/main_server/client_interface/json/?switcher=GetSearchResults&get_used_formats=1&services=1001

The JSON response contains two main objects: "meetings" and "formats".

If you call:

https://bmlt.newyorkna.org/main_server/client_interface/json/?switcher=GetSearchResults&get_formats_only=1&services=1001

Then only the "formats" object is returned.

Note that the "id" property of the "formats" object corresponds to the "id" field of the initial "?switcher=GetFormats" response.

Now, let's try the same thing with the worldwide Sandwich server:

https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetFormats

Note that the format IDs are now something more like "4282859624_2"

_**SIDE NOTE:** There is a "parent_id" property that is not required for formats. It does not [currently] cause any problems._

This is meetings only:

https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetSearchResults&services=1001

_**BUG:** These return nothing._

https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetSearchResults&get_used_formats=1&services=1001

https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetSearchResults&get_formats_only=1&services=1001

Note that the "id" property of the formats should match the ones in the main GetFormats call.

**Comment by radius314** [comment]
Can you update this bug, as some if may not be relevant anymore given that #20 was fixed.

**Comment by LittleGreenViper** [comment]
This appears to be fixed.
