### ISSUE TITLE
Service Body IDs Not Matching Between List and Search

### ISSUE THREAD

**Issue by LittleGreenViper** [radius314/sandwich#20]
If you query the World Sandwich Server for its Service Bodies:

https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetServiceBodies

It returns Service bodies with unique IDs (3758418901_1001 for Suffolk).

However, if you use this ID in searches, they fail:

https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetSearchResults&services=3758418901_1001

You need to use the native ID for the server:

https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetSearchResults&services=1001

**Comment by LittleGreenViper** [comment]
As an aside, I'd suggest losing the underscore (_). This forces handling of these IDs to be string. If we don't have that, then we can treat the ID as an integer.

**Comment by radius314** [comment]
Per our offline discussion will buffer with `000`

**Comment by radius314** [comment]
Underscores are gone now.

**Comment by radius314** [comment]
This has been fixed, please verify.

https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetSearchResults&services=1020001001

**Comment by LittleGreenViper** [comment]
Verified.

Thanks!

**Comment by radius314** [comment]
As a side note I noticed there are two different ways this gets passed `services[]` or `services`.  Can you comment on their differences?
