### ISSUE TITLE
Attach A URI Property to Search Results

### ISSUE THREAD

**Issue by LittleGreenViper** [radius314/sandwich#23]
This would be an enhancement request.

In the JSON response, each item should have a "uri" property. This would be a string property that would contain the Root Server URI for the server that sourced the item.

The rationale is that this could be a great way to provide a semantic "rabbit hole," that could be followed for more specific information about an item.

This would need to be attached to specific items (such as meetings, formats or Service bodies), as opposed to the aggregate collections, which, by definition, could contain items sourced from multiple servers.

**Comment by radius314** [comment]
What if this was in the HTTP response headers?  There could be a list of servers that responded.  In some cases it would be all the root servers that responded.  

This could add some overhead to the HTTP response.

**Comment by LittleGreenViper** [comment]
That wouldn't work. It needs to be in the JSON "leaf node" object.

That's because I need to be able to encapsulate handling of "leaf" nodes from the "root nodes" and "branches," if at all possible.

I don't want to have to sort through a global list to find just the one I need for this node.

**Comment by radius314** [comment]
Ok so to clarify.  You are looking for a specialized response body that segregates the response by root of response?

**Comment by LittleGreenViper** [comment]
No. Just an additional property of "leaf" nodes, that references the source root server.

The object is to allow us to do something like query a Root Server for things like format descriptions.


Little Green Viper Software Development LLC

Chris Marshall
Principal
chris@littlegreenviper.com <mailto:cmarshall@mac.com>
https://littlegreenviper.com <https://littlegreenviper.com/>

**Comment by radius314** [comment]
Sorry this is not clear to me still.

**Comment by LittleGreenViper** [comment]
OK. I'll walk through a scenario. I think this use case should explain it.

Say we are using the iOS app to send a query to two overlapping Root Servers. Root Server A has a format of "D" for "Discussion", but Root Server B has "Disability" for "D".

Now, the standard JSON response includes only the code abbreviations for a given meeting, so you may get two meetings that have the following codes:

"O,D,B"

Now, if they are in Root Server A, the "D" stands for "Discussion."

However, if they are in Server B, the "D" stands for "Disability" ("WC" on many servers).

Currently, the iOS app simply shows the codes, with no legend.

What I would like to be able to do, is go back to the Server that originated the meeting, and get the description for the relevant formats, so I can describe them to the user.

Is that clear?


Little Green Viper Software Development LLC

Chris Marshall
Principal
chris@littlegreenviper.com <mailto:cmarshall@mac.com>
https://littlegreenviper.com <https://littlegreenviper.com/>

**Comment by radius314** [comment]
Ok this problem set is clearer now.  Let me think about how we can address this.

**Comment by radius314** [comment]
Will not implement in favor of tomato.
