### ISSUE TITLE
quicksearch by state not working

### ISSUE THREAD

**Issue by radius314** [radius314/sandwich#24]
http://tkddevel.com/bmltwork/index.php/bmlt_quicksearch-states/

does not work

**Comment by radius314** [comment]
IDs related issue

https://na-bmlt.org/_/sandwich/client_interface/json/index.php?switcher=GetFieldValues&bmlt_settings_id=1497464282&meeting_key=location_province

**Comment by radius314** [comment]
Ok this is sort of related to #23.  The first is aggregating the response when including formats (which isn't working right now).   The second is then querying by the BMLT meeting id (id_bigint).   Since an ID would be repeated on a given root, there is no way to distinguish between various IDs.  We may have to prefix meeting ids as well to differentiate them.

**Comment by radius314** [comment]
This is the failing follow up query

https://na-bmlt.org/_/sandwich/client_interface/json/index.php?switcher=GetSearchResults&bmlt_settings_id=1497464282&get_used_formats=1&SearchString=1%2C2%2C4%2C5%2C6%2C7%2C39%2C45%2C46%2C97%2C100%2C110%2C111%2C142

**Comment by radius314** [comment]
This is sort of working now @littlegreenviper

**Comment by radius314** [comment]
@littlegreenviper can you point this to the tomato server? I want to validate that this can be fixed via migration.

**Comment by LittleGreenViper** [comment]
Nope. The satellite doesn't like Tomato.

**Comment by LittleGreenViper** [comment]
http://tkddevel.com/bmltwork/index.php/tomato-quicksearch/

**Comment by radius314** [comment]
looks good to me
