### ISSUE TITLE
Box boundaries are too strict causing results to not be returned.

### ISSUE THREAD

**Issue by radius314** [radius314/sandwich#30]
Example: 

/_/sandwich/client_interface/json/?switcher=GetSearchResults&sort_results_by_distance=1&long_val=-76.7260436&lat_val=34.7229391&geo_width=-10&weekdays[]=7&weekdays[]=1

Returns nothing, but:

https://bmlt.ncregion-na.org/main_server/client_interface/json/?switcher=GetSearchResults&sort_results_by_distance=1&long_val=-76.7260436&lat_val=34.7229391&geo_width=-10&weekdays[]=7&weekdays[]=1

Does.  

This is because this coordinate is just outside the bounds of the boundary box indicated.  The sandwich needs to look for nearby roots in this case.

**Comment by radius314** [comment]
@jbraswell this is an issue I knew would come up one day.  It's caused because the latitude an longitude falls right outside the boundary box of the closest root server.  

The boundary boxes are calculated from each root server and then cached so that on a search we are not having to hit all the root servers, but instead the ones that are within that boundary box.  I have some ideas, but I'm not sure quite what the right solution is.  Maybe @littlegreenviper has an idea.  

Here is a visual of the case above.  We are searching for a meeting Beaufort, NC, but it's not finding anything in Morehead City, NC which is just down the road.

<img width="607" alt="bmlt_live_tally" src="https://user-images.githubusercontent.com/1850811/35953842-8b07a73a-0c54-11e8-996d-7b4b98ff565d.png">

**Comment by LittleGreenViper** [comment]
You could add "padding" to the boundaries, but that won't fix all the issues.

	Chris Marshall
Principal
chris@littlegreenviper.com <mailto:chris@littlegreenviper.com>
https://littlegreenviper.com <https://littlegreenviper.com/>
Little Green Viper Software Development LLC

**Comment by radius314** [comment]
Will not patch this, as tomato resolves this.
