### ISSUE TITLE
Issue with low values for geo_width_km searches

### ISSUE THREAD

**Issue by paulnagle** [radius314/sandwich#31]
Hello!

I've been trying this out, and it's really cool.. Thought that you might to know that I came across an issue when I was trying out a few queries. It seems to be an issue with lower values for the geo_width_km param..

For example:

Does work:
https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetSearchResults&geo_width_km=50&long_val=-9.030&lat_val=51.578&sort_key=sort_results_by_distance&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_street,location_info,distance_in_km,latitude,longitude,formats&get_used_formats

Doesn't work
https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetSearchResults&geo_width_km=20&long_val=-9.030&lat_val=51.578&sort_key=sort_results_by_distance&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_street,location_info,distance_in_km,latitude,longitude,formats&get_used_formats

The only difference between the two searches is the range in kms.

I was thinking of using the sandwich link on the https://www.nasouth.ie/searchbymap.html page where you can choose the km range for searches between 1km and 99km, but as it stands this wont work for the smaller searches.

Thanks,
 Paul.

**Comment by radius314** [comment]
Thanks for reporting this, will take a look.

**Comment by radius314** [comment]
Ok, figure out what is going on here.  The underlying problem occurs because this meeting doesn't have a format.  The BMLT is masking this problem by not returning an empty array because `get_used_formats` is used.  If you set a format, this request should work.

Meeting request:

https://bmlt.nasouth.ie/main_server//client_interface/json/?switcher=GetSearchResults&geo_width_km=20&long_val=-9.030&lat_val=51.578&sort_key=sort_results_by_distance&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_street,location_info,distance_in_km,latitude,longitude,formats&get_used_formats&recursive=1

**Comment by paulnagle** [comment]
OK thanks for looking at this.. In the Ireland BMLT most meetings don't have a format associated with them, so I guess this is going to cause problems if we want to use the sandwich server.

**Comment by radius314** [comment]
This is a bug in the BMLT.  I've sent a request to @littlegreenviper to patch this up.

**Comment by LittleGreenViper** [comment]
OIC.

It's been sent to GitHub.

I just patched it in BitBucket.

I'm integrating it now, and will send it up to the TKD test server.

	Chris Marshall
Principal
chris@littlegreenviper.com <mailto:chris@littlegreenviper.com>
https://littlegreenviper.com <https://littlegreenviper.com/>
Little Green Viper Software Development LLC

**Comment by radius314** [comment]
@paulnagle can you try out against the latest `master` of the BMLT?

**Comment by paulnagle** [comment]
Sure. I had a go at pulling the latest files from master on bitbucket https://bitbucket.org/bmlt/bmlt-root-server/branch/master#commits and have them loaded onto bmlt.nasouth.ie.. I don't see any differences in any of my results though.

Does work:
https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetSearchResults&geo_width_km=50&long_val=-9.030&lat_val=51.578&sort_key=sort_results_by_distance&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_street,location_info,distance_in_km,latitude,longitude,formats&get_used_formats

Doesn't work
https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetSearchResults&geo_width_km=20&long_val=-9.030&lat_val=51.578&sort_key=sort_results_by_distance&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_street,location_info,distance_in_km,latitude,longitude,formats&get_used_formats

**Comment by LittleGreenViper** [comment]
This is weird. The 20Km should work fine, but I see it hanging.

https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetSearchResults&geo_width_km=20&long_val=-9.030&lat_val=51.578&sort_key=sort_results_by_distance&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_street,location_info,distance_in_km,latitude,longitude,formats&get_used_formats

However, directly to the NA Ireland server works:

https://bmlt.nasouth.ie/main_server/client_interface/json/?switcher=GetSearchResults&geo_width_km=20&long_val=-9.030&lat_val=51.578&sort_key=sort_results_by_distance&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_street,location_info,distance_in_km,latitude,longitude,formats&get_used_formats

**Comment by radius314** [comment]
Taking a look now.

**Comment by radius314** [comment]
https://bmlt.nasouth.ie/main_server//client_interface/json/?switcher=GetSearchResults&geo_width_km=20&long_val=-9.030&lat_val=51.578&sort_key=sort_results_by_distance&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_street,location_info,distance_in_km,latitude,longitude,formats&get_used_formats&recursive=1

Is still not returning the "get_used_formats" schema.

**Comment by LittleGreenViper** [comment]
Oh, I see. You want an empty object, even if there are no formats.

**Comment by radius314** [comment]
The schema should match as well.

**Comment by LittleGreenViper** [comment]
Hmm... the schema may be hosed. JSON Schema is worthless. No one uses it. I only do XML Schema.

I think I may have it nested incorrectly.

https://tkddevel.com/bmltwork/bmlt/main_server/client_interface/xsd/GetSearchResults.php

**Comment by radius314** [comment]
I guess what I mean is that if you make a request with `get_used_formats`, there are two separate objects returned in the response.  

Typical response schema:

![https___bmlt_nasouth_ie_main_server__client_interface_json__switcher_getsearchresults_geo_width_km_50_long_val_-9_030_lat_val_51_578_sort_key_sort_results_by_distance_data_field_key_meeting_name_weekday_tinyint_start_time_location_text_loca](https://user-images.githubusercontent.com/1850811/37257909-d24ddf42-2545-11e8-902c-74eb3e8b5a5b.png)

Anomaly response schema with a response with no formats set:

![https___bmlt_nasouth_ie_main_server__client_interface_json__switcher_getsearchresults_geo_width_km_20_long_val_-9_030_lat_val_51_578_sort_key_sort_results_by_distance_data_field_key_meeting_name_weekday_tinyint_start_time_location_text_loca](https://user-images.githubusercontent.com/1850811/37257915-ee9ba990-2545-11e8-82d6-2d4d92f01a64.png)

**Comment by radius314** [comment]
To clarify, if `get_used_formats`, sandwich assumes that `meetings` and `formats` will be part of the json object response.

**Comment by LittleGreenViper** [comment]
Oh...now I remember. The schema is correct. The formats and locationinfo are where they are supposed to be. I needed to keep the meetings as the root element.

Yeah, I can force an empty formats object there for JSON. With XML, it is optional. No formats, no object. XML has a lot of this kind of optimization. It tends to not include empty elements, and the JSON is derived from XML.

**Comment by LittleGreenViper** [comment]
Gotcher.

**Comment by radius314** [comment]
Requesting that `formats` is an empty array if none.

**Comment by LittleGreenViper** [comment]
I'll fix it, but remember that this will start in 2.10.1, and people tend to be a wee bit slow to upgrade...

**Comment by radius314** [comment]
Understood, this a rare instance.  Ireland is the first one to hit this bug.

**Comment by LittleGreenViper** [comment]
OK. I added it. One issue: I can't properly test it, as I don't have any datasets with zero formats.

**Comment by radius314** [comment]
I'll give it a spin.

**Comment by radius314** [comment]
still the same @LittleGreenViper 

one suggestion to test this.  add a meeting that is in a far off latitude and longitude and lower your search radius to 1 mile or km.

**Comment by LittleGreenViper** [comment]
OK. It will need a bit of time to address.

I'll have to run out for a little while.

	Chris Marshall
Principal
chris@littlegreenviper.com <mailto:chris@littlegreenviper.com>
https://littlegreenviper.com <https://littlegreenviper.com/>
Little Green Viper Software Development LLC

**Comment by LittleGreenViper** [comment]
Give it a spin now.

	Chris Marshall
Principal
chris@littlegreenviper.com <mailto:chris@littlegreenviper.com>
https://littlegreenviper.com <https://littlegreenviper.com/>
Little Green Viper Software Development LLC

**Comment by radius314** [comment]
Still not working.

**Comment by radius314** [comment]
Should look like this.  
![https___tomato_jbraz_com_main_server_client_interface_json__switcher_getsearchresults_geo_width_km_20_long_val_-9_030_lat_val_51_578_sort_key_sort_results_by_distance_data_field_key_meeting_name_weekday_tinyint_start_time_location_text_loca](https://user-images.githubusercontent.com/1850811/37266094-4672f32e-258e-11e8-976e-85a9d2cb1ee7.png)

**Comment by paulnagle** [comment]
Confirmed working. Its implemented on https://www.nasouth.ie/searchbymap.html now.

Thanks!

**Comment by radius314** [comment]
Great
