### ISSUE TITLE
A search that doesnt work through sandwich

### ISSUE THREAD

**Issue by paulnagle** [radius314/sandwich#33]
I've found a search url that doesn't seem to work via sandwich. The same url works fine through my local bmlt.

Works:
https://bmlt.nasouth.ie/main_server/client_interface/json/?switcher=GetSearchResults&geo_width_km=25&long_val=-9.31995759950951&lat_val=51.51084662925304&sort_key=sort_results_by_distance&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_street,location_info,distance_in_km,latitude,longitude,formats

Doesn't work:
https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetSearchResults&geo_width_km=25&long_val=-9.31995759950951&lat_val=51.51084662925304&sort_key=sort_results_by_distance&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_street,location_info,distance_in_km,latitude,longitude,formats

The search parameters are identical in both URLs.

**Comment by radius314** [comment]
Thanks @paulnagle.  Sandwich is going to be retired in the near term.  My recommendation is to use tomato, which is the future.

https://tomato.na-bmlt.org/main_server/client_interface/json/?switcher=GetSearchResults&geo_width_km=25&long_val=-9.31995759950951&lat_val=51.51084662925304&sort_key=sort_results_by_distance&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_street,location_info,distance_in_km,latitude,longitude,formats

**Comment by radius314** [comment]
https://github.com/jbraswell/tomato
