### ISSUE TITLE
CSV methods not working

### ISSUE THREAD

**Issue by BMLTGuy** [radius314/sandwich#9]
This concerns the demo "Whole World" aggregator [at this URI](http://bmlt-aggregator.archsearch.org/eccbc87e4b5ce2fe28308fd9f2a7baf3/bmltfed/main_server/).

When we query with [the Semantic Query for Service bodies](http://bmlt-aggregator.archsearch.org/eccbc87e4b5ce2fe28308fd9f2a7baf3/bmltfed/main_server/client_interface/csv/?switcher=GetServiceBodies), it eventually times out.

I believe that it should respond with all Service bodies, regardless of the number of them.

**Comment by radius314** [comment]
Ok it seems to be an issue of when you are trying to use csv format instead of json.  CSV was never implemented.  Is this a show-stopper for something?

**Comment by BMLTGuy** [comment]
I don't think so. However, it will be important for NAWS.



The Basic Meeting List Toolbox Admins
bmlt@magshare.net
http://bmlt.magshare.net/

**Comment by radius314** [comment]
Starting to think about this issue, would we expect to export every single meeting?  We are trying to build something that is going to useful for NAWS.

**Comment by BMLTGuy** [comment]
The World dump works on a hierarchical Service body mode. You could probably reroute NAWS dump calls directly to the relevant servers. I'd need to play this tape through, though...



The Basic Meeting List Toolbox Admins
bmlt@magshare.net
http://bmlt.magshare.net/

**Comment by radius314** [comment]
Yeah I would like to understand the best use case, since this seems like a feature that NAWS would like to use explicitly.  I can't think of a better consumer for it.

**Comment by BMLTGuy** [comment]
Well, We could create a fairly simple HTML page that they could use to trigger the extraction.

Maybe they load the page, and it runs all the Regions' NAWS dumps. We could hardcode the URLs, and just use AJAX to run the dumps; similar to the Tally app.



The Basic Meeting List Toolbox Admins
bmlt@magshare.net
http://bmlt.magshare.net/

**Comment by radius314** [comment]
Ideally they could just use the semantic workshop to do that.

**Comment by LittleGreenViper** [comment]
Yup. Let's close this bug.

**Comment by LittleGreenViper** [comment]
Yeah, that's what I mean. I don't think there's a need for Sandwich to support this. We need to know the RSC's ID and server anyway, so we can go directly to the Root Server.
I guess we could create a "dispatcher" site that lists the RSCs, with links to each dump, but I don't think we need Sandwich for that. We could use the Tally list.

**Comment by radius314** [comment]
Why not dump all of them?

**Comment by LittleGreenViper** [comment]
We could do that, but it would be quite slow.

Remember also, that NAWS' preferred granularity is the RSC level. Many servers (like GNYR's) have more than one RSC.

I've tried to get NAWS to consider pulling the dumps themselves, but they have resisted the idea.

**Comment by radius314** [comment]
I guess one challenge I can think of is that some BMLTs list meetings that they do not export because they are not directly responsible for them.

**Comment by LittleGreenViper** [comment]
I don't think that any BMLT server should ever list a meeting that is not one they are directly responsible for.

For example, if someone lists the meetings for a neighboring ASC in their server, but the neighboring ASC is not participating in maintaining their list on that server, then, in my opinion, that ASC's meetings should be removed from the server.

It is bad, bad, BAD to maintain separate databases.

Bad.

BAD.

VERY VERY BAD.

ARMAGEDDON BAD.

I cannot stress enough how bad this is, which is one reason that I'm so upset that NAWS deliberately chooses to maintain a separate database that they know to be inaccurate.

Whenever this happens, I always get people snarling at me that I'm "insulting" them by "doubting" them. They assure me that they will maintain the separate databases.

Then, they fail to do so.

EVERY. SINGLE. TIME.

WITHOUT FAIL, THEY FAIL.

If a meeting is in a BMLT database, then that should be the single place the meeting is maintained. If someone wants to get their listing from that place (like NAWS should), and display it separately, then that's -sort of- OK.

**Comment by radius314** [comment]
Not saying I disagree.  This is reality versus the ideal.  I think maybe a simple page on sandwich that gives a list of all the CSV links.

**Comment by BMLTGuy** [comment]
We could do that. However, it needs to present them as RSC level. That means some "smart parsing" of the semantic response to pick out RSCs, and build the list, based on that.

Alternatively, we could hand-curate this, but it could get hairy.

There's a couple of Root Servers that don't have RSCs, and there are probably ones that don't have the entire RSC in them (I think that the CARNA server may have a couple of partials).

	The Basic Meeting List Toolbox
Project Administrators
bmlt@magshare.net <mailto:chris@littlegreenviper.com>
https://bmlt.magshare.net <https://bmlt.magshare.net/>

**Comment by radius314** [comment]
This will be implemented in the replacement to sandwich... https://github.com/jbraswell/tomato.
